---
- hosts: runtime_host
  vars_files:
    - vars.yaml
  tasks:
    - name: Copy and unarchive the package into the indicators runtime host directory.
      unarchive:
        src: "{{ jenkins_artifact_dir }}/{{ package }}"
        dest: "{{ indicators_runtime_dir }}"
        owner: "{{ runtime_user }}"
        group: "{{ runtime_user }}"

    - name: Mutate Python bin path used in venv.
      file:
        src: "{{ pyenv_python_path }}"
        dest: "{{ indicators_runtime_dir }}/{{ indicator }}/env/bin/python"
        owner: "{{ runtime_user }}"
        group: "{{ runtime_user }}"
        state: link

    - name: Set production params file.
      copy:
        src: files/{{ indicator }}-params-prod.json
        dest: "{{ indicators_runtime_dir }}/{{ indicator }}/params.json"
        owner: "{{ runtime_user }}"
        group: "{{ runtime_user }}"
