---
- hosts: all
  become: yes
  vars_files:
    - vars.yaml
  tasks:
    - name: Copy and unarchive the package into the indicators runtime host directory.
      unarchive:
        src: "{{ jenkins_artifact_dir }}/{{ package }}"
        dest: "{{ indicator_runtime_dir }}"
        owner: automation
        group: automation

    - name: Mutate Python bin path used in venv.
      file:
        src: "{{ pyenv_python_path }}"
        dest: "{{ indicator_runtime_dir }}/{{ indicator }}/env/bin/python"
        owner: automation
        group: automation
        state: link

    - name: Set production params file.
      copy:
        src: files/{{ indicator }}-params-prod.json
        dest: "{{ indicator_runtime_dir }}/{{ indicator }}/params.json"
        owner: automation
        group: automation
