---
- hosts: all
  become: yes
  vars_files:
    - vars.yaml
  tasks:
    - name: Copy and unarchive the package into the indicators runtime host directory
      unarchive:
        src: "{{ jenkins_artifact_dir }}/{{ package }}"
        dest: "{{ indicator_runtime_dir }}"
        owner: automation
        group: automation

    # - name: Place production config json file.
      
# Mutate json config
# Run! Do we add this here as well? Maybe better to schedule it via automation?
