---
jenkins_artifact_dir: "/var/lib/jenkins/artifacts"
# indicator_code_dir: "/home/automation/driver/delphi/covidcast-indicators"
indicator_runtime_dir: "/tmp"
indicator: "{{ "" }}" # This will be passed in at runtime.
package: "{{ indicator }}.tar.gz"
