---
jenkins_artifacts_dir: "/var/lib/jenkins/artifacts"
# indicators_code_dir: "/home/automation/driver/delphi/covidcast-indicators"
indicators_code_dir: "/tmp"
indicator: "{{ indicator }}"
package: "{{ indicator }}".tar.gz
midas_server: "delphi-master-prod-01.delphi.cmu.edu"
