---
jenkins_artifact_dir: "/var/lib/jenkins/artifacts"
indicator_runtime_dir: "/home/automation/driver/delphi/covidcast-indicators"
package: "{{ indicator }}.tar.gz" # This is passed in the Ansible invocation.
python_version: "3.8.2"
pyenv_python_path: "/home/automation/.pyenv/versions/{{ python_version }}/bin/python"
