# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        packages: [usafacts, cdc_covidnet]
    defaults:
      run:
        working-directory: Python-packages/covidcast-py/${{ matrix.packages }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install package and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ../_delphi_utils_python/
        pip install .
    - name: Lint with pylint
      run: |
        pylint ${{ matrix.packages }}
    - name: Test with pytest
      run: |
        (cd tests && ../env/bin/pytest)
